unique_ids:
  assets:
    512x512OsloconWorkout.png: '1775835646126723964615455.6954'
    standard-page.html: JYQ4XBFA2VLQLJE5JMSSNLTVYVXJ5TKS
    theme.css: IO2B77CU47C67TLPDE7RMJB3UNSLSTJS
  forms:
    Form1: UZPXHXCDUE6VJWJOITPGOZT5D3XVXQAD
  modules: {}
  scripts: {}
  server_modules: {}
